-- 報銷明細存下「掃到的電子發票 QR 左碼原文」與「使用者選了哪個稅額來源」。
--
-- ★ 為什麼要存 qr_payload：**進項稅額的信任邊界搬回伺服端**。
--   在此之前，前端傳一個 sales_amount（未稅銷售額）上來，伺服端拿它算
--   「總額 − 銷售額 = 進項稅」——等於任何人都能把任意金額宣稱成進項稅
--   （amount 10000、sales_amount 0 → 進項稅 10000 元進 401）。
--   改成前端傳 QR 原文、伺服端自己解析並與明細欄位交叉核對之後，
--   這串原文就是那個數字唯一的出處，必須跟著明細一起留著。
--
-- ★ 為什麼**不**另存 sales_amount：它從 qr_payload 導得出來。存兩份會漂移
--   （本 repo 的既有紀律：清單／常數只寫一次），而且多一個可被獨立寫入的數字
--   就是多一個繞過解析的入口。
--
-- ★ 為什麼要存 tax_source：退回重送（PATCH /expense-claims/:id）會把明細
--   整批刪掉重建。沒有這兩欄，使用者原本選的稅額來源會被無聲換回費率回推——
--   那正是這一包要擋的「系統替使用者做了一個他不知道的決定」。
--   存了之後伺服端重送時自己重新推導，不必再問使用者一次。
--
-- 兩欄都允許 NULL：既有明細沒有 QR 也沒有做過選擇，那是事實，不要用預設值假裝有。
-- tax_source 不做成 enum：它只有伺服端寫入（值域由 zod 與 services/expenses.ts 把關），
-- 為兩個字串新增一個型別，日後要加第三種來源就得再一支 migration。
ALTER TABLE expense_items ADD COLUMN qr_payload text;
ALTER TABLE expense_items ADD COLUMN tax_source text;
