import type { Dictionary } from "@tw-erp/core";

export const allowanceXml: Dictionary = {
  "銷貨退回／折讓單不存在: {id}": "Sales return/allowance note not found: {id}",
  "折讓單 #{id} 是退回單，不是折讓單。G0401 目前只支援折讓（官方範例僅涵蓋折讓的表達方式）；退回的證明單請以財政部軟體或加值中心平台開立後，回到銷貨頁補登號碼": "Note #{id} is a return, not an allowance. G0401 currently supports allowances only (the official samples only cover allowances). Issue the return certificate with the MOF software or a value-added center platform, then record its number on the Sales page",
  "折讓單 #{id} 還沒登錄證明單號碼{missing}，產不出 G0401。號碼由貴公司自行編定（即 XML 的 AllowanceNumber）、日期是折讓證明單的開立日；請到銷貨頁的「退貨／折讓紀錄」補登後再下載": "Allowance note #{id} has no certificate number{missing} recorded yet, so G0401 cannot be generated. The number is assigned by your company (the AllowanceNumber in the XML) and the date is the certificate's issue date. Record them under \"Returns / Allowances\" on the Sales page, then download again",
  "折讓單 #{id} 的證明單號碼「{certNo}」含有英數、連字號、底線以外的字元，不能作為 G0401 的 AllowanceNumber 與檔名。請修改號碼後再下載": "The certificate number \"{certNo}\" on allowance note #{id} contains characters other than letters, digits, hyphens and underscores, so it cannot be used as the G0401 AllowanceNumber or file name. Change the number and download again",
  "折讓單 #{id} 的原銷貨單 #{saleId} 沒有已開立的電子發票，產不出 G0401（折讓證明單的明細必須指回原發票號碼）。原銷貨若是紙本或免開發票的交易，證明單請以財政部軟體開立；發票被作廢過的請先重新開立": "The original sales invoice #{saleId} for allowance note #{id} has no issued e-invoice, so G0401 cannot be generated (allowance certificate lines must reference the original invoice number). If the original sale was paper-invoiced or invoice-exempt, issue the certificate with the MOF software; if the invoice was voided, re-issue it first",
  "#{id} 是退回單，不是折讓單。G0501 只作廢本系統產出的 G0401 折讓證明單；退回的證明單是以外部工具開立的，其作廢也請在原開立工具處理": "#{id} is a return, not an allowance. G0501 only voids G0401 allowance certificates produced by this system; return certificates are issued with external tools, so void them there as well",
  "折讓單 #{id} 尚未作廢，沒有作廢訊息可產。G0501 是「作廢折讓證明單」的對外訊息，請先在銷貨頁作廢這張折讓單": "Allowance note #{id} has not been voided, so there is no void message to generate. G0501 is the outbound \"void allowance certificate\" message; void the allowance note on the Sales page first",
  "折讓單 #{id} 作廢前沒有登錄過證明單號碼與日期，表示從未產出 G0401——沒有開立訊息就沒有要作廢的對外訊息，帳務面的作廢已經完成，不需要 G0501": "Allowance note #{id} had no certificate number or date recorded before it was voided, meaning G0401 was never produced. With no issue message there is nothing to void externally; the accounting void is already complete and no G0501 is needed",
  "折讓單 #{id} 沒有記錄作廢理由（資料異常，請聯絡管理者）——G0501 的 CancelReason 必填": "Allowance note #{id} has no void reason recorded (data inconsistency, contact an admin). CancelReason is required in G0501",
  "折讓單 #{id} 的原銷貨單 #{saleId} 沒有任何電子發票紀錄，取不到買方統編，產不出 G0501（這張折讓的證明單若是以外部工具開立的，其作廢也請在原開立工具處理）": "The original sales invoice #{saleId} for allowance note #{id} has no e-invoice record, so the buyer's Tax ID is unavailable and G0501 cannot be generated (if this allowance certificate was issued with an external tool, void it there as well)",
};
