import type { Dictionary } from "@tw-erp/core";

export const taxParameters: Dictionary = {
  "一列參數只能有一種值：級距與是／否二選一。兩種都填的話取數時無從決定要看哪一個，而那個歧義只會在幾個月後某張單據算錯時才浮出來": "A parameter row can hold only one kind of value: either brackets or yes/no. If both are filled, lookups cannot tell which to use, and that ambiguity only surfaces months later when a document is calculated wrong",
  "這一列沒有值：級距型參數請至少填一個級距，是／否型參數請選「是」或「否」": "This row has no value: bracket parameters need at least one bracket, and yes/no parameters need \"Yes\" or \"No\" selected",
  "生效起日須為 YYYY-MM-DD: {value}": "Effective start date must be YYYY-MM-DD: {value}",
  "生效迄日須為 YYYY-MM-DD: {value}": "Effective end date must be YYYY-MM-DD: {value}",
  "生效迄日 {to} 早於起日 {from}：這一列會永遠解析不到任何日期，而畫面上它看起來跟正常的列一樣。迄日留空代表「仍有效」": "Effective end date {to} is earlier than start date {from}: this row would never match any date, yet it would look like a normal row on screen. Leave the end date blank to mean \"still in effect\"",
  "級距設定有問題：{problems}": "Bracket settings are invalid: {problems}",
  "請給這一列一個看得懂的名稱（例如「營業稅率」「6137 交際費可否扣抵」）": "Give this row a recognizable name (e.g. \"VAT rate\", \"6137 Entertainment expense deductible\")",
  "新列的生效起日 {from} 早於既有的第 #{id} 列（{latestFrom} 起）。參數只能往未來延伸——往回插一列會改變「過去某一天該用哪個值」，等於讓已經算過的年度算不回來。若你正在補建歷史費率，請由舊到新依序新增；若要更正的是既有那一列的值，請新增一列從「更正生效日」起接續，並在依據來源欄寫明更正了哪一列": "The new row's effective start date {from} is earlier than existing row #{id} (effective from {latestFrom}). Parameters can only extend into the future: inserting an earlier row would change which value applied on a past date, so already-calculated years could no longer be reproduced. If you are backfilling historical rates, add them in order from oldest to newest; to correct an existing row's value, add a new row that supersedes it from the correction date and note which row it corrects in the Source field",
  "找不到可接續的前一列：第 #{id} 列的生效起日與新列同為 {from}，接續會把它的迄日設成起日的前一天（期間顛倒）。本表刻意 append-only——舊年度必須算得回來，所以不提供「改掉填錯的那一列」。若這一列從第一天就填錯，請新增一列從「更正生效日」起接續，並在依據來源欄寫明「更正第 #{id} 列」；已依錯誤值建立的單據不會回頭重算，需要更正的請自行判斷處理方式（沖銷重開或手工傳票）": "No previous row to supersede: row #{id} has the same effective start date as the new row ({from}), and superseding it would set its end date to the day before its start (an inverted period). This table is deliberately append-only so prior years can always be reproduced, which is why \"edit the wrong row\" is not offered. If that row was wrong from day one, add a new row that supersedes it from the correction date and note \"corrects row #{id}\" in the Source field. Documents already created with the wrong value are not recalculated; decide how to correct them yourself (reverse and re-issue, or a manual journal voucher)",
  "找不到可接續的前一列（同一種參數在 {from} 之前沒有仍生效的設定）。這是第一列的話請取消「接續前一列」直接新增": "No previous row to supersede (no setting for this parameter is in effect before {from}). If this is the first row, uncheck \"Supersede previous row\" and add it directly",
  "生效期間與第 #{id} 列「{label}」（{period}）重疊。同一種參數在同一天只能有一個值，否則單據要用哪一個沒有答案。若這是新費率取代舊費率，請勾選「接續前一列」——系統會把第 #{id} 列的迄日設為 {dayBefore}，舊列的值與依據都原樣保留": "The effective period overlaps row #{id} \"{label}\" ({period}). A parameter can have only one value on any given day, otherwise documents have no way to choose. If this new rate replaces the old one, check \"Supersede previous row\": the system will set row #{id}'s end date to {dayBefore} and keep the old row's value and source unchanged",
};
