import type { Dictionary } from "@tw-erp/core";

export const vat: Dictionary = {
  "公司稅籍編號或縣市別未設定（PUT /company-profile）": "Company tax registration number or city code is not set (PUT /company-profile)",
  "公司基本檔標記為「兼營免稅／特種稅額」：兼營的營業稅申報要用 403 申報書（含不得扣抵比例計算），本系統目前只支援 401（專營應稅），不產出 401 以免錯用申報書類別。請以財政部申報軟體或洽記帳士辦理 403 申報；若貴公司實為專營應稅，請到「設定」頁取消該標記": "The company profile is flagged as \"mixed taxable/exempt (special tax) business\". Mixed businesses must file a VAT return on Form 403 (including the non-deductible ratio calculation). This system only supports Form 401 (fully taxable), so no 401 file is produced to avoid filing on the wrong form. File Form 403 with the MOF filing software or through your bookkeeper; if your company is actually fully taxable, clear the flag on the Settings page",
  "進項發票之供應商缺少統一編號": "The supplier on an input invoice has no Tax ID",
  "申報人身分證統一編號超過 10 碼或含全形字元，請到「設定」頁公司基本檔更正": "The filer's National ID exceeds 10 characters or contains full-width characters. Correct it in the company profile on the Settings page",
  "期別 {period} 已有申報紀錄（#{id}）。更正申報請先刪除該期紀錄（只能刪最新一期）再重新存檔——刪除後其後期別的留抵承轉會跟著改變，請依期別順序重存": "A VAT return already exists for period {period} (#{id}). To file an amendment, delete that period's record first (only the latest period can be deleted), then save again. Deleting it changes the carried-forward credit for later periods, so re-save them in period order",
  "已存在較晚期別（{later}）的申報紀錄，不可回頭補存 {period}——較晚期別的上期留抵已經定案，往回插一期會讓它失去來歷。若順序真的錯了，請從最新一期開始逐期刪除後依序重存": "A VAT return for a later period ({later}) already exists, so {period} cannot be saved retroactively. The later period's opening credit is already fixed; inserting an earlier period would break its lineage. If the order is really wrong, delete returns one period at a time starting from the latest, then re-save them in order",
  "期別 {period} 沒有申報紀錄": "No VAT return found for period {period}",
  "期別 {later} 的申報紀錄以 {period} 的期末留抵為基礎，不可先刪除 {period}。請從最新一期開始逐期刪除": "The VAT return for period {later} is based on the closing credit of {period}, so {period} cannot be deleted first. Delete returns one period at a time starting from the latest",
  "手動輸入的上期留抵 {manual} 元與上期（{prevPeriod}）申報紀錄的期末留抵 {filed} 元不一致——請確認以哪一個為準（申報紀錄在「營業稅申報」頁下方）。": "The manually entered prior-period carryover NT${manual} differs from the closing carryover NT${filed} in the filed return for {prevPeriod} — confirm which one is correct (filed returns are listed at the bottom of the VAT Return page).",
  "找不到上期（{prevPeriod}）的申報紀錄，上期累積留抵以 0 帶入——但系統裡有其他期別的申報紀錄，留抵承轉在這裡斷了鏈。請確認上期是否漏存，或在畫面手動輸入正確的上期留抵。": "No filed return found for the prior period ({prevPeriod}); the prior-period carryover is set to 0 — but the system has filed returns for other periods, so the carryover chain is broken here. Check whether the prior period was not saved, or enter the correct prior-period carryover manually.",
  "找不到上期（{prevPeriod}）的申報紀錄，上期累積留抵（申報書代號 108）以 0 帶入。第一次用本系統申報屬正常；若上期實際有留抵，請在畫面輸入金額後重新產出。本期申報完成後按「存為申報紀錄」，下期即可自動承轉。": "No filed return found for the prior period ({prevPeriod}); the prior-period carryover (return code 108) is set to 0. This is normal for the first return filed with this system; if there actually was a carryover, enter the amount and regenerate. After filing this period, click \"Save as filed return\" so the next period carries it forward automatically.",
  "申報人姓名或身分證統一編號未設定，申報書第 99-103 欄將是空白——請到「設定」頁的公司基本檔填寫申報人資料（委託記帳士申報則另填代理申報人登錄字號）。": "The filer's name or National ID is not set, so fields 99-103 of the return will be blank — fill in the filer details in Company Profile on the Settings page (if a bookkeeper files on your behalf, also enter the agent registration number).",
  "本期有 {n} 張進貨單（#{ids}）沒登錄供應商發票日期，進項歸期以進貨單日期代替。發票開立月份與進貨月份不同時，會與賣方申報的期別勾稽不符——請到「進貨」頁按「改發票資訊」補上發票日期後重新產出本期申報檔。": "{n} purchase invoices this period (#{ids}) have no supplier invoice date, so the purchase invoice date was used to assign the input period. If the invoice month differs from the purchase month, it will not reconcile with the seller's filing period — open the Purchases page, click \"Edit invoice info\" to add the invoice dates, then regenerate this period's filing.",
  "本期有 {n} 筆零稅率銷貨（合計 {sum} 元）還沒登錄證明文件號碼（經海關＝出口報單號碼；非經海關＝外匯證明文件號碼等）。金額已列入申報書的零稅率銷售額，但申報零稅率需檢附證明文件——請到「銷貨」頁補登號碼，或確認該單是否真為零稅率。": "{n} zero-rated sales this period (totaling NT${sum}) have no supporting document number (via customs = export declaration number; not via customs = foreign exchange certificate number, etc.). The amounts are included in the return's zero-rated sales, but zero-rated filing requires supporting documents — add the numbers on the Sales page, or confirm whether those sales are really zero-rated.",
  "零稅率銷售額已列入申報書（代號 7／15／19／23）。得退稅限額與應退稅額（代號 113／114）本系統不計算（其計算規則未經規格書查證），一律填 0＝溢付稅額全額留抵到下期；若要申請退稅，請以財政部申報軟體匯入後的計算為準。": "Zero-rated sales are included in the return (codes 7/15/19/23). The refund ceiling and refundable tax (codes 113/114) are not calculated by this system (their rules have not been verified against the spec) and are always 0, meaning any overpaid tax is carried forward in full to the next period; to claim a refund, rely on the calculation after importing into the Ministry of Finance filing software.",
  "媒體檔中零稅率銷項明細的「通關方式註記」（第 81 碼）未填——該欄的代號值未經作業要點原文核對（見 docs/specs/vat-401-403.md 未決問題），匯入財政部申報軟體後請依實際通關方式補正。": "The \"customs clearance mark\" (position 81) on zero-rated output lines in the media file is left blank — its code values have not been verified against the official guidelines (see open issues in docs/specs/vat-401-403.md); after importing into the Ministry of Finance filing software, correct it per the actual clearance method.",
};
